-- =====================================================================
-- ASETS 0001 — core schema
--
-- Conventions used throughout:
--   * money       NUMERIC(12,2) — never float. Floats lose pennies, and
--                 these figures end up on an HMRC submission.
--   * quantities  NUMERIC(12,3) — supports part-hours (1.5, 0.25).
--   * ids         uuid, generated by the database (gen_random_uuid).
--   * time        timestamptz, always UTC; dates that belong to the tax
--                 year (issue_date, expense_date) are plain DATE.
--   * deletion    soft (deleted_at) for anything an accountant may need
--                 to see again; hard only on account deletion.
--   * isolation   row-level security keyed on asets.user_id, so a query
--                 that forgets its WHERE clause returns nothing instead
--                 of another practitioner's books.
-- =====================================================================

CREATE SCHEMA IF NOT EXISTS asets;
SET search_path = asets, public;

-- ---------------------------------------------------------------------
-- Helpers
-- ---------------------------------------------------------------------

-- Current tenant, as set by the application at the start of every
-- transaction. Unset -> NULL -> every RLS policy denies. Default deny is
-- the whole point.
CREATE OR REPLACE FUNCTION asets.current_user_id() RETURNS uuid
LANGUAGE sql STABLE AS $$
  SELECT NULLIF(current_setting('asets.user_id', true), '')::uuid
$$;

CREATE OR REPLACE FUNCTION asets.touch_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END
$$;

-- ---------------------------------------------------------------------
-- Enumerations
-- ---------------------------------------------------------------------
CREATE TYPE asets.invoice_status AS ENUM ('draft', 'sent', 'paid');
CREATE TYPE asets.service_unit   AS ENUM ('session', 'hour', 'fixed');

-- ---------------------------------------------------------------------
-- users — one practitioner, one row
-- ---------------------------------------------------------------------
CREATE TABLE asets.users (
    id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    email           text          NOT NULL,
    password_hash   text          NOT NULL,
    name            text          NOT NULL DEFAULT '',
    business_name   text          NOT NULL DEFAULT '',
    address         text          NOT NULL DEFAULT '',
    city            text          NOT NULL DEFAULT '',
    postcode        text          NOT NULL DEFAULT '',
    utr             text          NOT NULL DEFAULT '',
    company_reg     text          NOT NULL DEFAULT '',
    vat_number      text          NOT NULL DEFAULT '',
    ni_number       text          NOT NULL DEFAULT '',
    -- Bank details are shown on invoices; they are the user's own payee
    -- details, not a payment instrument, so they live with the profile.
    bank_name       text          NOT NULL DEFAULT '',
    bank_account_name text        NOT NULL DEFAULT '',
    bank_sort_code  text          NOT NULL DEFAULT '',
    bank_account_number text      NOT NULL DEFAULT '',
    bank_reference  text          NOT NULL DEFAULT 'Please use the invoice number',
    -- UI preferences only. Nothing here is ever used in a calculation,
    -- which is why it is allowed to be schemaless.
    settings        jsonb         NOT NULL DEFAULT
                      '{"theme":"system","cards":["take_home","hmrc","cashflow","recent"]}'::jsonb,
    created_at      timestamptz   NOT NULL DEFAULT now(),
    updated_at      timestamptz   NOT NULL DEFAULT now(),
    deleted_at      timestamptz,
    CONSTRAINT users_email_shape CHECK (email ~ '^[^@[:space:]]+@[^@[:space:]]+\.[^@[:space:]]+$'),
    CONSTRAINT users_settings_is_object CHECK (jsonb_typeof(settings) = 'object')
);

-- Case-insensitive uniqueness without depending on the citext extension:
-- managed Postgres providers differ on which extensions they allow, and a
-- functional index needs none of them. The application lowercases on the
-- way in; this catches anything that does not.
CREATE UNIQUE INDEX users_email_key ON asets.users (lower(email));

CREATE TRIGGER users_touch BEFORE UPDATE ON asets.users
  FOR EACH ROW EXECUTE FUNCTION asets.touch_updated_at();

-- ---------------------------------------------------------------------
-- user_services — the practitioner's price list
-- ---------------------------------------------------------------------
CREATE TABLE asets.user_services (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL REFERENCES asets.users(id) ON DELETE CASCADE,
    name        text NOT NULL,
    price       numeric(12,2),
    unit        asets.service_unit NOT NULL DEFAULT 'session',
    created_at  timestamptz NOT NULL DEFAULT now(),
    CONSTRAINT user_services_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT user_services_price_non_negative CHECK (price IS NULL OR price >= 0)
);
CREATE INDEX user_services_user_idx ON asets.user_services (user_id);
CREATE UNIQUE INDEX user_services_unique_name ON asets.user_services (user_id, lower(name));

-- ---------------------------------------------------------------------
-- clients
-- ---------------------------------------------------------------------
CREATE TABLE asets.clients (
    id             uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id        uuid NOT NULL REFERENCES asets.users(id) ON DELETE CASCADE,
    name           text NOT NULL,
    contact_name   text NOT NULL DEFAULT '',
    email          text NOT NULL DEFAULT '',
    address        text NOT NULL DEFAULT '',
    company_number text NOT NULL DEFAULT '',
    notes          text NOT NULL DEFAULT '',
    rate           numeric(12,2),
    created_at     timestamptz NOT NULL DEFAULT now(),
    updated_at     timestamptz NOT NULL DEFAULT now(),
    deleted_at     timestamptz,
    CONSTRAINT clients_name_not_blank CHECK (btrim(name) <> ''),
    CONSTRAINT clients_rate_non_negative CHECK (rate IS NULL OR rate >= 0),
    CONSTRAINT clients_company_number_shape CHECK (company_number = '' OR company_number ~ '^[A-Za-z0-9]{1,12}$')
);
-- Every client list is "mine, not deleted, by name": index exactly that.
CREATE INDEX clients_live_idx ON asets.clients (user_id, name) WHERE deleted_at IS NULL;
CREATE TRIGGER clients_touch BEFORE UPDATE ON asets.clients
  FOR EACH ROW EXECUTE FUNCTION asets.touch_updated_at();

-- ---------------------------------------------------------------------
-- invoices
-- ---------------------------------------------------------------------
CREATE TABLE asets.invoices (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id     uuid NOT NULL REFERENCES asets.users(id) ON DELETE CASCADE,
    client_id   uuid NOT NULL REFERENCES asets.clients(id) ON DELETE RESTRICT,
    number      text NOT NULL,
    issue_date  date NOT NULL,
    due_date    date,
    status      asets.invoice_status NOT NULL DEFAULT 'sent',
    notes       text NOT NULL DEFAULT '',
    -- Maintained by trigger from invoice_items. Denormalised on purpose:
    -- every dashboard read sums invoices, none of them wants a join.
    total       numeric(12,2) NOT NULL DEFAULT 0,
    paid_date   date,
    emailed_at  date,
    created_at  timestamptz NOT NULL DEFAULT now(),
    updated_at  timestamptz NOT NULL DEFAULT now(),
    deleted_at  timestamptz,
    CONSTRAINT invoices_total_non_negative CHECK (total >= 0),
    CONSTRAINT invoices_due_after_issue CHECK (due_date IS NULL OR due_date >= issue_date),
    -- A paid invoice has a paid date; an unpaid one must not.
    CONSTRAINT invoices_paid_date_matches_status CHECK (
        (status = 'paid' AND paid_date IS NOT NULL) OR
        (status <> 'paid' AND paid_date IS NULL)
    ),
    -- Composite key so invoice_items can carry user_id without it ever
    -- disagreeing with the parent invoice.
    CONSTRAINT invoices_id_user_key UNIQUE (id, user_id)
);
CREATE UNIQUE INDEX invoices_number_per_user ON asets.invoices (user_id, number) WHERE deleted_at IS NULL;
CREATE INDEX invoices_live_idx ON asets.invoices (user_id, issue_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX invoices_status_idx ON asets.invoices (user_id, status) WHERE deleted_at IS NULL;
CREATE INDEX invoices_client_idx ON asets.invoices (client_id) WHERE deleted_at IS NULL;
CREATE TRIGGER invoices_touch BEFORE UPDATE ON asets.invoices
  FOR EACH ROW EXECUTE FUNCTION asets.touch_updated_at();

-- ---------------------------------------------------------------------
-- invoice_items
-- ---------------------------------------------------------------------
CREATE TABLE asets.invoice_items (
    id          uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    invoice_id  uuid NOT NULL,
    user_id     uuid NOT NULL,
    position    integer NOT NULL,
    description text NOT NULL DEFAULT '',
    quantity    numeric(12,3) NOT NULL DEFAULT 1,
    unit_price  numeric(12,2) NOT NULL DEFAULT 0,
    line_total  numeric(12,2) GENERATED ALWAYS AS (round(quantity * unit_price, 2)) STORED,
    CONSTRAINT invoice_items_quantity_positive CHECK (quantity > 0),
    CONSTRAINT invoice_items_price_non_negative CHECK (unit_price >= 0),
    CONSTRAINT invoice_items_position_positive CHECK (position > 0),
    FOREIGN KEY (invoice_id, user_id)
        REFERENCES asets.invoices (id, user_id) ON DELETE CASCADE
);
CREATE INDEX invoice_items_invoice_idx ON asets.invoice_items (invoice_id, position);
CREATE UNIQUE INDEX invoice_items_position_key ON asets.invoice_items (invoice_id, position);

-- Keep invoices.total honest no matter who writes to invoice_items.
CREATE OR REPLACE FUNCTION asets.refresh_invoice_total() RETURNS trigger
LANGUAGE plpgsql AS $$
DECLARE
    target uuid := COALESCE(NEW.invoice_id, OLD.invoice_id);
BEGIN
    UPDATE asets.invoices i
       SET total = COALESCE((SELECT sum(line_total) FROM asets.invoice_items WHERE invoice_id = target), 0)
     WHERE i.id = target;
    RETURN NULL;
END
$$;

CREATE TRIGGER invoice_items_total AFTER INSERT OR UPDATE OR DELETE ON asets.invoice_items
  FOR EACH ROW EXECUTE FUNCTION asets.refresh_invoice_total();

-- ---------------------------------------------------------------------
-- expense_categories — a lookup, so a typo can never create a category
-- ---------------------------------------------------------------------
CREATE TABLE asets.expense_categories (
    code      text PRIMARY KEY,
    label     text NOT NULL,
    position  integer NOT NULL,
    -- Which box this maps to on an HMRC self-employment submission.
    hmrc_field text NOT NULL
);

INSERT INTO asets.expense_categories (code, label, position, hmrc_field) VALUES
    ('Software',          'Software',            1, 'adminCosts'),
    ('Supervision',       'Supervision',         2, 'professionalFees'),
    ('Training / CPD',    'Training / CPD',      3, 'otherExpenses'),
    ('Insurance',         'Insurance',           4, 'premisesRunningCosts'),
    ('Professional fees', 'Professional fees',   5, 'professionalFees'),
    ('Office / Rent',     'Office / Rent',       6, 'premisesRunningCosts'),
    ('Equipment',         'Equipment',           7, 'adminCosts'),
    ('Phone / Internet',  'Phone / Internet',    8, 'adminCosts'),
    ('Travel',            'Travel',              9, 'carVanTravelExpenses'),
    ('Other',             'Other',              10, 'otherExpenses');

-- ---------------------------------------------------------------------
-- expenses
-- ---------------------------------------------------------------------
CREATE TABLE asets.expenses (
    id           uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    user_id      uuid NOT NULL REFERENCES asets.users(id) ON DELETE CASCADE,
    category     text NOT NULL REFERENCES asets.expense_categories(code) ON UPDATE CASCADE,
    description  text NOT NULL DEFAULT '',
    amount       numeric(12,2) NOT NULL,
    expense_date date NOT NULL,
    receipt_path text,
    created_at   timestamptz NOT NULL DEFAULT now(),
    updated_at   timestamptz NOT NULL DEFAULT now(),
    deleted_at   timestamptz,
    CONSTRAINT expenses_amount_non_negative CHECK (amount >= 0)
);
CREATE INDEX expenses_live_idx ON asets.expenses (user_id, expense_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX expenses_category_idx ON asets.expenses (user_id, category) WHERE deleted_at IS NULL;
CREATE TRIGGER expenses_touch BEFORE UPDATE ON asets.expenses
  FOR EACH ROW EXECUTE FUNCTION asets.touch_updated_at();

-- ---------------------------------------------------------------------
-- Row-level security
--
-- users is deliberately excluded: login has to find a row by email
-- before any tenant is known. Everything downstream of that is fenced.
-- ---------------------------------------------------------------------
DO $$
DECLARE t text;
BEGIN
  FOREACH t IN ARRAY ARRAY['user_services','clients','invoices','invoice_items','expenses']
  LOOP
    EXECUTE format('ALTER TABLE asets.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('ALTER TABLE asets.%I FORCE ROW LEVEL SECURITY', t);
    EXECUTE format($f$
      CREATE POLICY tenant_isolation ON asets.%I
        USING (user_id = asets.current_user_id())
        WITH CHECK (user_id = asets.current_user_id())
    $f$, t);
  END LOOP;
END
$$;
