#!/usr/bin/env python3
"""Generate every secret ASETS needs, once.

    python3 scripts/gen_secrets.py                 # write backend/.env
    python3 scripts/gen_secrets.py --print         # show them, write nothing
    python3 scripts/gen_secrets.py --gcp PROJECT   # also push to Secret Manager

What gets generated here, and why it cannot be regenerated casually:

  JWT_SECRET            signs session tokens. Rotating it signs everyone out.
  TOKEN_ENCRYPTION_KEY  encrypts HMRC tokens and NI numbers at rest.
                        Rotating it makes existing HMRC connections
                        undecryptable — every user has to reconnect.
  DB_APP_PASSWORD       the application's PostgreSQL role (asets_app).

Nothing here is written to git: backend/.env is ignored.
"""
import argparse
import base64
import os
import secrets
import subprocess
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
ENV_FILE = ROOT / "backend" / ".env"

# Secret Manager names for the values that must never sit in a deploy command.
GCP_SECRETS = ("JWT_SECRET", "TOKEN_ENCRYPTION_KEY", "DB_APP_PASSWORD",
               "DATABASE_URL", "ANTHROPIC_API_KEY", "HMRC_CLIENT_SECRET",
               "COMPANIES_HOUSE_API_KEY")


def fernet_key() -> str:
    """32 random bytes, urlsafe-base64 — the format Fernet expects."""
    return base64.urlsafe_b64encode(secrets.token_bytes(32)).decode()


def db_password() -> str:
    """Alphanumeric: DSN parsing and pooler auth both dislike punctuation."""
    alphabet = "abcdefghijkmnopqrstuvwxyzABCDEFGHJKLMNPQRSTUVWXYZ23456789"
    return "".join(secrets.choice(alphabet) for _ in range(32))


def generate() -> dict:
    return {
        "JWT_SECRET": secrets.token_urlsafe(48),
        "TOKEN_ENCRYPTION_KEY": fernet_key(),
        "DB_APP_PASSWORD": db_password(),
        "DEMO_ACCOUNT_PASSWORD": db_password()[:16],
    }


TEMPLATE = """# ASETS backend configuration — generated by scripts/gen_secrets.py
# NEVER COMMIT THIS FILE. Regenerating JWT_SECRET signs everyone out;
# regenerating TOKEN_ENCRYPTION_KEY forces every user to reconnect to HMRC.

# --- Database --------------------------------------------------------------
DATABASE_URL=postgresql://asets_app:{DB_APP_PASSWORD}@127.0.0.1:5432/asets
# Supabase (session pooler):
#   postgresql://asets_app.<project-ref>:PASSWORD@aws-0-<region>.pooler.supabase.com:5432/postgres?sslmode=require
DB_APP_PASSWORD={DB_APP_PASSWORD}

# --- Secrets ---------------------------------------------------------------
JWT_SECRET={JWT_SECRET}
TOKEN_ENCRYPTION_KEY={TOKEN_ENCRYPTION_KEY}

# --- CORS ------------------------------------------------------------------
CORS_ORIGINS=*

# --- Receipt storage -------------------------------------------------------
# postgres = images stored in the database (no object store to run)
# local    = a mounted disk, if you would rather keep them out of the DB
STORAGE_BACKEND=postgres

# --- Receipt scanning (optional) ------------------------------------------
LLM_PROVIDER=anthropic
ANTHROPIC_API_KEY=
RECEIPT_MODEL=claude-opus-5

# --- Companies House lookup (optional, free key) --------------------------
COMPANIES_HOUSE_API_KEY=

# --- HMRC Making Tax Digital ----------------------------------------------
# Register the application at developer.service.hmrc.gov.uk, subscribe to
# Business Details, Obligations, Self Employment Business and Individual
# Calculations, then paste the sandbox credentials here.
HMRC_ENVIRONMENT=sandbox
HMRC_CLIENT_ID=
HMRC_CLIENT_SECRET=
HMRC_REDIRECT_URI=http://localhost:8080/api/hmrc/callback
HMRC_APP_RETURN_URL=asets://hmrc
HMRC_PRODUCT_NAME=ASETS
HMRC_SERVER_VERSION=1.0.0
# Fill in after the first deploy: the API's outbound public IP.
HMRC_VENDOR_PUBLIC_IP=

# --- Demo / store-reviewer account ----------------------------------------
DEMO_ACCOUNT_PASSWORD={DEMO_ACCOUNT_PASSWORD}
"""


def push_to_gcp(project: str, values: dict) -> None:
    for name in GCP_SECRETS:
        value = values.get(name, "")
        if not value:
            print(f"  · {name} — skipped (no value yet; create it when you have one)")
            continue
        exists = subprocess.run(
            ["gcloud", "secrets", "describe", name, f"--project={project}"],
            capture_output=True).returncode == 0
        if not exists:
            subprocess.run(["gcloud", "secrets", "create", name, "--replication-policy=automatic",
                            f"--project={project}"], check=True, capture_output=True)
        subprocess.run(["gcloud", "secrets", "versions", "add", name, "--data-file=-",
                        f"--project={project}"], input=value.encode(), check=True,
                       capture_output=True)
        print(f"  ✓ {name}")


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__,
                                 formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--print", dest="show", action="store_true", help="print only, write nothing")
    ap.add_argument("--force", action="store_true", help="overwrite an existing backend/.env")
    ap.add_argument("--gcp", metavar="PROJECT", help="also store secrets in GCP Secret Manager")
    args = ap.parse_args()

    values = generate()

    if args.show:
        for key, value in values.items():
            print(f"{key}={value}")
        return 0

    if ENV_FILE.exists() and not args.force:
        print(f"✗ {ENV_FILE} already exists.\n"
              f"  Refusing to overwrite live secrets — pass --force if that is really what you want.",
              file=sys.stderr)
        return 1

    ENV_FILE.parent.mkdir(parents=True, exist_ok=True)
    ENV_FILE.write_text(TEMPLATE.format(**values))
    os.chmod(ENV_FILE, 0o600)
    print(f"✓ wrote {ENV_FILE} (mode 600, git-ignored)")
    print("\nGenerated:")
    for key in values:
        print(f"  · {key}")
    print("\nStill to fill in by hand (they come from other people's consoles):")
    print("  · ANTHROPIC_API_KEY          console.anthropic.com")
    print("  · HMRC_CLIENT_ID / SECRET    developer.service.hmrc.gov.uk")
    print("  · COMPANIES_HOUSE_API_KEY    developer.company-information.service.gov.uk")

    if args.gcp:
        print(f"\nPushing to Secret Manager in {args.gcp}:")
        push_to_gcp(args.gcp, values)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
