// Design tokens — ASETS (ADHD Self-Employed Taxes Support)
// Palette: whites + soft blues + Hinomaru red (#BC002D). Japanese, calm, empowering.
export const palette = {
  light: {
    surface: "#F6F9FC",
    onSurface: "#16202B",
    surfaceSecondary: "#FFFFFF",
    onSurfaceSecondary: "#16202B",
    surfaceTertiary: "#EAF1F8",
    onSurfaceTertiary: "#54657A",
    surfaceInverse: "#16202B",
    onSurfaceInverse: "#F6F9FC",
    brand: "#3E6FA8",
    brandPrimary: "#3E6FA8",
    onBrandPrimary: "#FFFFFF",
    brandSecondary: "#BC002D",
    onBrandSecondary: "#FFFFFF",
    brandTertiary: "#DDE9F5",
    onBrandTertiary: "#284A70",
    success: "#3E6FA8",
    onSuccess: "#FFFFFF",
    warning: "#BC002D",
    onWarning: "#FFFFFF",
    error: "#BC002D",
    onError: "#FFFFFF",
    info: "#6E96C8",
    onInfo: "#FFFFFF",
    border: "#DCE6F0",
    borderStrong: "#B7C7D9",
    divider: "#E6EDF4",
  },
  dark: {
    surface: "#0E1622",
    onSurface: "#EAF1F8",
    surfaceSecondary: "#17212F",
    onSurfaceSecondary: "#EAF1F8",
    surfaceTertiary: "#1F2C3D",
    onSurfaceTertiary: "#9DB1C7",
    surfaceInverse: "#F6F9FC",
    onSurfaceInverse: "#0E1622",
    brand: "#6FA1D6",
    brandPrimary: "#6FA1D6",
    onBrandPrimary: "#0E1622",
    brandSecondary: "#E23B57",
    onBrandSecondary: "#FFFFFF",
    brandTertiary: "#213248",
    onBrandTertiary: "#AECAE8",
    success: "#6FA1D6",
    onSuccess: "#0E1622",
    warning: "#E23B57",
    onWarning: "#FFFFFF",
    error: "#E23B57",
    onError: "#FFFFFF",
    info: "#6FA1D6",
    onInfo: "#0E1622",
    border: "#273649",
    borderStrong: "#3B4F66",
    divider: "#243343",
  },
};

export type ThemeColors = typeof palette.light;

export const spacing = { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, "2xl": 32, "3xl": 48 };
export const radius = { sm: 6, md: 12, lg: 20, pill: 999 };
export const fontSize = { sm: 12, base: 14, lg: 16, xl: 20, "2xl": 24, "3xl": 32, "4xl": 40 };
